### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by nil123532** [metadriverse/pvp#1]
Hi, 
Please update code on setting up. 
I have been getting a lot of issues and can't run the code.

**Comment by nil123532** [comment]
Kind reminder about this project's code.

**Comment by nil123532** [comment]
why is the code not released yet?

**Comment by pengzhenghao** [comment]
Hi, thanks for reaching out! Thank you for your paientice!

I was on my winter break after NeurIPS and am now back to work.

Yea I am finalizing the release of the code. Though we have the implementation on our hand, I want to make sure it's most up to date, easy to understand and reproducible. The implementation will be finalized within this week. Please stay tuned!

**Comment by nil123532** [comment]
Thank you. 
Wondering if we will be able to use the code on any gym environments

**Comment by pengzhenghao** [comment]
> we will be able to use the code on any gym environments

It's possible only if the action space of the environment is compatible with the human control device, or at least you should have some approaches to interpret the human input actions into the real action space of the RL environment.

Thanks for reminding me that I should add a section discussing how we can use the same codebase to try new environments. Basically, the user need to implement a gym wrapper that can take human action as input and add some fields into the info dict return by the environment.

**Comment by nil123532** [comment]
a gym wrapper that resembles the minigridwrapper?

**Comment by nil123532** [comment]
hi I am having some issue for this. 
My environment just freezes and the agent's action always say "None"

NOTE: I am using my own environment
