### ISSUE TITLE
!!PVP implementation in carla -urgent !!

### ISSUE THREAD

**Issue by Shivasairudrangi** [metadriverse/pvp#12]
HI all ,
please helps to solve this problem urgent please 
![pvpimage](https://github.com/metadriverse/pvp/assets/120459769/3b26c0a5-fb67-4170-adeb-2014c7e556ce)

**Comment by pengzhenghao** [comment]
Seems like MetaDrive version issue. Is this issue still exists now? What MetaDrive version you are using?

**Comment by ml6362662** [comment]
> 似乎是 MetaDrive 版本问题。这个问题现在还存在吗？您使用的是哪个 MetaDrive 版本？

I also encountered this problem, by looking up the file I found that there is no 'TakeoverPolicyWithoutBrake' function, but there is a 'TakeoverPolicy' function, I changed the function name to 'TakeoverPolicy' and there is no such error, but it produces a new error, I don't know how to solve it.

![2024-08-10 19-56-36屏幕截图](https://github.com/user-attachments/assets/4cfb25f3-0492-4c3d-b0f8-7fb6991ae27d)

(pvp) hff@hff-ubuntu:/mnt/share/pvp$ python pvp/experiments/metadrive/train_pvp_metadrive.py --device keyboard --toy_env --exp_name pvp_metadrive_toy_keyboard
[WARNING] Please note that you are not using wandb right now!!!
We start logging training data into runs/pvp_metadrive_toy_keyboard_keyboard/pvp_metadrive_toy_keyboard_keyboard_2024-08-10_19-55-57
[INFO] Environment: HumanInTheLoopEnv
[INFO] MetaDrive version: 0.4.2.2
[INFO] Sensors: [lidar: Lidar(), side_detector: SideDetector(), lane_line_detector: LaneLineDetector(), main_camera: MainCamera(1600, 1100), dashboard: DashBoard()]
[INFO] Render Mode: onscreen
[INFO] Horizon (Max steps per agent): None
[INFO] Another instance of this program is already running. Wait for the asset pulling finished from another program...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...

**Comment by pengzhenghao** [comment]
This is the internet connection issue please use VPN
