### ISSUE TITLE
Unable to Find 'OLD' Folder - Need Assistance for PVP Model Evaluation in CARLA

### ISSUE THREAD

**Issue by Shivasairudrangi** [metadriverse/pvp#13]
Hi,

I hope this message finds you well. My name is Shivasai, and I am a final-year B.Tech student deeply impressed by your work on the PVP model.

I am currently working on implementing the PVP model but have encountered an issue. I cannot find the folder named 'OLD', which is preventing me from running any of the evaluation scripts in CARLA. As my project deadline is approaching soon, I would greatly appreciate your guidance and support in resolving this issue.

Thank you for your time and assistance.

Best regards,
Shivasai

https://github.com/metadriverse/pvp/blob/main/pvp/eval_script/carla/carla_eval_utils.py#L12

**Comment by pengzhenghao** [comment]
Sorry for the inconvineance. Could you try this PR: #14 to see if everything works?

**Comment by Shivasairudrangi** [comment]
Thank you for your reply !
im getting  errors 

my present error is 
![image](https://github.com/metadriverse/pvp/assets/120459769/f130f25e-0c12-42d6-b910-523a69bd89c1)

i feel there was a issue with environment .
 while   running below step im getting error  :
 error: di-engine 0.2.2 requires gym==0.20.0, but you have gym 0.19.0 which is incompatible.
 
# Step 4: Install dependencies
pip install DI-engine==0.2.2
pip install torchvision
pip install markupsafe==2.0.1
https://github.com/metadriverse/PVP


please help me !!!! urgent
