### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by neugzy** [metadriverse/pvp#15]
Hi,

I encountered some issues while reproducing the metadrive vp code, such as the inability to render lane lines, lawns, and other content, as shown in the following image. But it can sense content such as double yellow lines. Could you help me?
![QQ20240712-225833](https://github.com/user-attachments/assets/6cd8971d-fb28-427f-af88-116bfc7b751f)

Best regards,
neugzy

**Comment by coco-suda** [comment]
> Oh, this problem has been solved. I try it successfully in conda base environment, but failed in other conda environment. It is a little strange, but i solved it anyway. If you encounter the same problem, you can also use this method. If it still cannot be resolved, it is recommended to reinstall Anaconda or the computer system. 哦，这个问题已经解决了。我在conda基础环境中成功地尝试了它，但在其他conda环境中失败了。这有点奇怪，但无论如何我还是解决了。如果你遇到同样的问题，你也可以使用这种方法。如果仍然无法解决，建议重新安装Anaconda或计算机系统。

你好，请问方便加个联系方式沟通一下复现情况吗？我的邮箱是txx310925@163.com

**Comment by neugzy** [comment]
> > Oh, this problem has been solved. I try it successfully in conda base environment, but failed in other conda environment. It is a little strange, but i solved it anyway. If you encounter the same problem, you can also use this method. If it still cannot be resolved, it is recommended to reinstall Anaconda or the computer system. 哦，这个问题已经解决了。我在conda基础环境中成功地尝试了它，但在其他conda环境中失败了。这有点奇怪，但无论如何我还是解决了。如果你遇到同样的问题，你也可以使用这种方法。如果仍然无法解决，建议重新安装Anaconda或计算机系统。
> 
> 你好，请问方便加个联系方式沟通一下复现情况吗？我的邮箱是[txx310925@163.com](mailto:txx310925@163.com)

发你邮箱了，欢迎互相交流

**Comment by pengzhenghao** [comment]
Does this problem still exist? Seems like a python environment issue. Close for now.
