### ISSUE TITLE
could you please release 

### ISSUE THREAD

**Issue by SHITIANYU-hue** [metadriverse/pvp#21]
could you please also provide some details or release the GTA V customized environment? 

![image](https://github.com/user-attachments/assets/329ae952-77fe-4340-89cb-a331fdd947fe)

**Comment by pengzhenghao** [comment]
We probably can't release about it.. The coauthor who worked out the GTA5 environment is no longer accessible.. Sorry about that. Our code is adapted from:

https://github.com/aitorzip/DeepGTAV

**Comment by pengzhenghao** [comment]
But overall, we just copy the design of MetaDrive, and it's a RL environment which provides 1D lidar scan of the surrounding. We also have some waypoints information in obs. (which just like the 1-to-1 copy of metadrive). The reward config is also copied from metadrive.
